language: objective-c
osx_image: xcode7.3
cache: cocoapods

before_install:
  - brew update
  - brew install swiftlint
  - gem install cocoapods
  - pod repo update --silent
  - gem install xcpretty

script:
  - swiftlint
  - set -o pipefail && xcodebuild -workspace iOSBasicTraining.xcworkspace -scheme 'iOSBasicTraining' -destination 'platform=iOS Simulator,name=iPhone 6s Plus' build test CODE_SIGN_IDENTITY=- | xcpretty -c

