osx_image: xcode7.3
language: objective-c
xcode_workspace: iOSBasicTraining.xcworkspace
xcode_scheme: iOSBasicTraining
cache: cocoapods

script:
  - xctool -workspace iOSBasicTraining.xcworkspace -scheme iOSBasicTraining build CODE_SIGN_IDENTITY=""  CODE_SIGNING_REQUIRED=NO
